[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/about-me"
  to = "/#about"
  status = 301

[[redirects]]
  from = "/about"
  to = "/#about"
  status = 301
